//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type User struct {
	Idx       int32 `sql:"primary_key"`
	ID        string
	Passwd    string
	CreatedAt time.Time
	UpdatedAt *time.Time
	Name      string
	Email     string
	Role      int32
}
