//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Proof struct {
	Idx             int32
	Category        string
	Description     string
	FirstImagePath  *string
	SecondImagePath *string
	LogPath         *string
	CreatedUserIdx  *int32
	CreatedAt       time.Time
	UpdatedUserIdx  *int32
	UpdatedAt       *time.Time
	UploadedUserIdx *int32
	UploadedAt      *time.Time
	Confirm         int32
	Num             *string
	TokenID         *int32
}
