// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import v1 "buf.build/gen/go/wanho/security-proof-api/protocolbuffers/go/api/v1"

type ControllerConverterImpl struct{}

func (c *ControllerConverterImpl) CreateRequestToUser(source *v1.CreateUserRequest) *v1.User {
	var pApiv1User *v1.User
	if source != nil {
		var apiv1User v1.User
		apiv1User.Id = (*source).Id
		apiv1User.Passwd = (*source).Passwd
		apiv1User.Name = (*source).Name
		apiv1User.Email = (*source).Email
		apiv1User.Role = (*source).Role
		pApiv1User = &apiv1User
	}
	return pApiv1User
}
func (c *ControllerConverterImpl) DeleteRequestToUser(source *v1.DeleteUserRequest) *v1.User {
	var pApiv1User *v1.User
	if source != nil {
		var apiv1User v1.User
		apiv1User.Idx = (*source).Idx
		pApiv1User = &apiv1User
	}
	return pApiv1User
}
func (c *ControllerConverterImpl) SignInRequestToUser(source *v1.SignInRequest) *v1.User {
	var pApiv1User *v1.User
	if source != nil {
		var apiv1User v1.User
		apiv1User.Id = (*source).Id
		apiv1User.Passwd = (*source).Passwd
		pApiv1User = &apiv1User
	}
	return pApiv1User
}
func (c *ControllerConverterImpl) UpdateRequestToUser(source *v1.UpdateUserRequest) *v1.User {
	var pApiv1User *v1.User
	if source != nil {
		var apiv1User v1.User
		apiv1User.Idx = (*source).Idx
		apiv1User.Name = (*source).Name
		apiv1User.Email = (*source).Email
		apiv1User.Role = (*source).Role
		pApiv1User = &apiv1User
	}
	return pApiv1User
}
